version: 2.1
jobs:
  build:
    docker:
      - image: bridgecrew/checkov
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            pip install checkov

      - run:
          name: the second stage
          command: |
            ls -al
            helm version
            pwd
            checkov -f /root/project/rendered.yml
             
